### ISSUE TITLE
Property 'toBeSameSecondAs' does not exist on type 'JestMatchersShape<Matchers<void, Date | null | undefined>, Matchers<Promise<void>, Date | null | undefined>>

### ISSUE THREAD

**Issue by jeznag** [pkuczynski/jest-date#64]
I've set up jest.config.js with ```    "setupFilesAfterEnv": ['jest-date'] ```

(I also tried a separate setup file)

**Comment by gpbl** [comment]
@jeznag check you are setting up it correctly:

In `jest.config.ts`:

```diff
export default {
  roots: ['./src'],
  transform: {
    '^.+\\.tsx?$': 'ts-jest'
  },
  moduleFileExtensions: ['ts', 'tsx', 'json', 'js', 'node'],
  coverageReporters: ['lcov', 'text', 'clover'],
+ setupFilesAfterEnv: ['./jest.setup.ts']
};
```

in `jest.setup.ts`:

```diff
+ import 'jest-date';
```

Thanks @stefan-wullems for the plug-in!

**Comment by pkuczynski** [comment]
This should be working in the last version. if not, please let me know and I will try to debug.
